language: cpp

branches:
  only:
    - master

compiler:
  - gcc

before_install:
  - sudo apt-get install libace-dev
  - sudo apt-get update 

script:
  - test -d build || mkdir build
  - test -d install || mkdir install
  - cd build
  - cmake -DPCH=0 -DCMAKE_BUILD_TYPE=Release -DUSE_STD_MALLOC=1 -DACE_USE_EXTERNAL=1 -DCMAKE_INSTALL_PREFIX=../install ..
  - make -j4

notifications:
  irc:
    channels:
      - "irc.rizon.net#mangosR2"
    on_success: never
    on_failure: never
